// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package models

// BatchUpdateSdResourceRequest defines model for BatchUpdateSdResourceRequest.
type BatchUpdateSdResourceRequest struct {
	// Cpu sd function cpu
	Cpu *float32 `json:"cpu,omitempty"`

	// Env sd env
	Env *map[string]interface{} `json:"env,omitempty"`

	// ExtraArgs sd start args
	ExtraArgs *string `json:"extraArgs,omitempty"`

	// GpuMemorySize GPU Video RAM
	GpuMemorySize *int64 `json:"gpuMemorySize,omitempty"`

	// Image sd image
	Image *string `json:"image,omitempty"`

	// InstanceType fc.gpu.tesla.1:T4, fc.gpu.ampere.1:A10
	InstanceType *string `json:"instanceType,omitempty"`

	// MemorySize instance mem size (MB)
	MemorySize *int64 `json:"memorySize,omitempty"`

	// Models sd models list, not set default all
	Models *[]string `json:"models,omitempty"`

	// NasConfig nas config
	NasConfig *map[string]interface{} `json:"nasConfig,omitempty"`

	// OssMountConfig oss config
	OssMountConfig *map[string]interface{} `json:"ossMountConfig,omitempty"`

	// Timeout fucntion timeout
	Timeout *int64 `json:"timeout,omitempty"`

	// VpcConfig vpc config
	VpcConfig *map[string]interface{} `json:"vpcConfig,omitempty"`
}

// BatchUpdateSdResourceResponse defines model for BatchUpdateSdResourceResponse.
type BatchUpdateSdResourceResponse struct {
	// ErrMsg fail message
	ErrMsg *string `json:"errMsg,omitempty"`

	// FailFuncList fail function list
	FailFuncList *[]string `json:"failFuncList,omitempty"`

	// Status update status val(success\fail)
	Status *string `json:"status,omitempty"`
}

// DelSDFunctionRequest defines model for DelSDFunctionRequest.
type DelSDFunctionRequest struct {
	// Functions del functions
	Functions *[]string `json:"functions,omitempty"`
}

// DelSDFunctionResponse defines model for DelSDFunctionResponse.
type DelSDFunctionResponse struct {
	// Fails fail delete functions
	Fails *[]map[string]interface{} `json:"fails,omitempty"`

	// Status success|fail
	Status *string `json:"status,omitempty"`
}

// Error defines model for Error.
type Error struct {
	// Code Error code
	Code int64 `json:"code"`

	// Message Error message
	Message string `json:"message"`
}

// ExtraImagesRequest defines model for ExtraImagesRequest.
type ExtraImagesRequest struct {
	ForceTaskId       		  *string  `json:"force_task_id,omitempty"`
	CodeformerVisibility      *float32 `json:"codeformer_visibility,omitempty"`
	CodeformerWeight          *float32 `json:"codeformer_weight,omitempty"`
	ExtrasUpscaler2Visibility *float32 `json:"extras_upscaler_2_visibility,omitempty"`
	GfpganVisibility          *float32 `json:"gfpgan_visibility,omitempty"`
	Image                     string   `json:"image"`
	ResizeMode                int64    `json:"resize_mode"`
	ShowExtrasResults         *bool    `json:"show_extras_results,omitempty"`
	StableDiffusionModel      *string  `json:"stable_diffusion_model,omitempty"`
	UpscaleFirst              *bool    `json:"upscale_first,omitempty"`
	Upscaler1                 *string  `json:"upscaler_1,omitempty"`
	Upscaler2                 *string  `json:"upscaler_2,omitempty"`
	UpscalingCrop             *bool    `json:"upscaling_crop,omitempty"`
	UpscalingResize           *float32 `json:"upscaling_resize,omitempty"`
	UpscalingResizeH          *int64   `json:"upscaling_resize_h,omitempty"`
	UpscalingResizeW          *int64   `json:"upscaling_resize_w,omitempty"`
}

// Img2ImgRequest defines model for Img2ImgRequest.
type Img2ImgRequest struct {
	ForceTaskId       				  *string  				  `json:"force_task_id,omitempty"`
	AlwaysonScripts                   *map[string]interface{} `json:"alwayson_scripts,omitempty"`
	BatchSize                         *int64                  `json:"batch_size,omitempty"`
	CfgScale                          *float32                `json:"cfg_scale,omitempty"`
	DenoisingStrength                 *float32                `json:"denoising_strength,omitempty"`
	DoNotSaveGrid                     *bool                   `json:"do_not_save_grid,omitempty"`
	DoNotSaveSamples                  *bool                   `json:"do_not_save_samples,omitempty"`
	Eta                               *int64                  `json:"eta,omitempty"`
	Height                            *int64                  `json:"height,omitempty"`
	ImageCfgScale                     *float32                `json:"image_cfg_scale,omitempty"`
	IncludeInitImages                 *bool                   `json:"include_init_images,omitempty"`
	InitImages                        *[]string               `json:"init_images,omitempty"`
	InitialNoiseMultiplier            *int64                  `json:"initial_noise_multiplier,omitempty"`
	InpaintFullRes                    *bool                   `json:"inpaint_full_res,omitempty"`
	InpaintFullResPadding             *int64                  `json:"inpaint_full_res_padding,omitempty"`
	InpaintingFill                    *int64                  `json:"inpainting_fill,omitempty"`
	InpaintingMaskInvert              *int64                  `json:"inpainting_mask_invert,omitempty"`
	Mask                              *string                 `json:"mask,omitempty"`
	MaskBlur                          *int64                  `json:"mask_blur,omitempty"`
	MaskBlurX                         *int64                  `json:"mask_blur_x,omitempty"`
	MaskBlurY                         *int64                  `json:"mask_blur_y,omitempty"`
	NIter                             *int64                  `json:"n_iter,omitempty"`
	NegativePrompt                    *string                 `json:"negative_prompt,omitempty"`
	OverrideSettings                  *map[string]interface{} `json:"override_settings,omitempty"`
	OverrideSettingsRestoreAfterwards *bool                   `json:"override_settings_restore_afterwards,omitempty"`
	Prompt                            *string                 `json:"prompt,omitempty"`
	ResizeMode                        *int64                  `json:"resize_mode,omitempty"`
	RestoreFaces                      *bool                   `json:"restore_faces,omitempty"`
	SChurn                            *int64                  `json:"s_churn,omitempty"`
	SMinUncond                        *int64                  `json:"s_min_uncond,omitempty"`
	SNoise                            *int64                  `json:"s_noise,omitempty"`
	STmax                             *int64                  `json:"s_tmax,omitempty"`
	STmin                             *int64                  `json:"s_tmin,omitempty"`
	SamplerIndex                      *string                 `json:"sampler_index,omitempty"`
	SamplerName                       *string                 `json:"sampler_name,omitempty"`
	SaveDir                           *string                 `json:"save_dir,omitempty"`
	SaveImages                        *bool                   `json:"save_images,omitempty"`
	ScriptArgs                        *[]interface{}          `json:"script_args,omitempty"`
	ScriptName                        *string                 `json:"script_name,omitempty"`
	SdVae                             *string                 `json:"sd_vae,omitempty"`
	Seed                              *int64                  `json:"seed,omitempty"`
	SeedResizeFromH                   *int64                  `json:"seed_resize_from_h,omitempty"`
	SeedResizeFromW                   *int64                  `json:"seed_resize_from_w,omitempty"`
	SendImages                        *bool                   `json:"send_images,omitempty"`
	StableDiffusionModel              string                  `json:"stable_diffusion_model"`
	Steps                             *int64                  `json:"steps,omitempty"`
	Styles                            *[]string               `json:"styles,omitempty"`
	Subseed                           *int64                  `json:"subseed,omitempty"`
	SubseedStrength                   *float32                `json:"subseed_strength,omitempty"`
	Tiling                            *bool                   `json:"tiling,omitempty"`
	Width                             *int64                  `json:"width,omitempty"`
}

// ListSDFunctionResponse defines model for ListSDFunctionResponse.
type ListSDFunctionResponse struct {
	// ErrMsg fail message
	ErrMsg *string `json:"errMsg,omitempty"`

	// Functions dynamically creating functions
	Functions *[]map[string]interface{} `json:"functions,omitempty"`

	// Status success|fail
	Status *string `json:"status,omitempty"`
}

// Model defines model for Model.
type Model struct {
	// Name model name
	Name string `json:"name"`

	// OssPath the oss path of the model
	OssPath string `json:"ossPath"`

	// Type model type
	Type string `json:"type"`
}

// ModelAttributes defines model for ModelAttributes.
type ModelAttributes struct {
	// Etag the oss etag of the model
	Etag string `json:"etag"`

	// LastModificationTime the last modification time of the model
	LastModificationTime *string `json:"lastModificationTime,omitempty"`

	// Name model name
	Name string `json:"name"`

	// OssPath the oss path of the model
	OssPath string `json:"ossPath"`

	// RegisteredTime the registered time of the model
	RegisteredTime *string `json:"registeredTime,omitempty"`

	// Status the model status, registering, loading, loaded or unloaded
	Status string `json:"status"`

	// Type model type
	Type string `json:"type"`
}

// OptionRequest config params
type OptionRequest struct {
	Data map[string]interface{} `json:"data"`
}

// ResponseMessage response message
type ResponseMessage struct {
	Message string `json:"message"`
}

// SubmitTaskResponse defines model for SubmitTaskResponse.
type SubmitTaskResponse struct {
	Message *string `json:"message,omitempty"`

	// OssUrl oss url
	OssUrl *[]string `json:"ossUrl,omitempty"`
	Status string    `json:"status"`
	TaskId string    `json:"taskId"`
}

// TaskProgressResponse defines model for TaskProgressResponse.
type TaskProgressResponse struct {
	CurrentImage string                  `json:"currentImage"`
	EtaRelative  float32                 `json:"etaRelative"`
	Message      *string                 `json:"message,omitempty"`
	Progress     float32                 `json:"progress"`
	State        *map[string]interface{} `json:"state,omitempty"`
	TaskId       string                  `json:"taskId"`
}

// TaskResultResponse one task result, include taskId/images/parameters/info
type TaskResultResponse struct {
	// Images one task image result, len(images)>1 when batch count or batch size > 1
	Images *[]string `json:"images,omitempty"`

	// Info task predict info
	Info    *map[string]interface{} `json:"info,omitempty"`
	Message *string                 `json:"message,omitempty"`

	// OssUrl oss url
	OssUrl *[]string `json:"ossUrl,omitempty"`

	// Parameters task predict params
	Parameters *map[string]interface{} `json:"parameters,omitempty"`
	Status     string                  `json:"status"`
	TaskId     string                  `json:"taskId"`
}

// Txt2ImgRequest defines model for Txt2ImgRequest.
type Txt2ImgRequest struct {
	ForceTaskId       				  string  				  `json:"force_task_id,omitempty"`
	AlwaysonScripts                   *map[string]interface{} `json:"alwayson_scripts,omitempty"`
	BatchSize                         *int64                  `json:"batch_size,omitempty"`
	CfgScale                          *float32                `json:"cfg_scale,omitempty"`
	DenoisingStrength                 *float32                `json:"denoising_strength,omitempty"`
	DoNotSaveGrid                     *bool                   `json:"do_not_save_grid,omitempty"`
	DoNotSaveSamples                  *bool                   `json:"do_not_save_samples,omitempty"`
	EnableHr                          *bool                   `json:"enable_hr,omitempty"`
	Eta                               *int64                  `json:"eta,omitempty"`
	FirstphaseHeight                  *int64                  `json:"firstphase_height,omitempty"`
	FirstphaseWidth                   *int64                  `json:"firstphase_width,omitempty"`
	Height                            *int64                  `json:"height,omitempty"`
	HrNegativePrompt                  *string                 `json:"hr_negative_prompt,omitempty"`
	HrPrompt                          *string                 `json:"hr_prompt,omitempty"`
	HrResizeX                         *int64                  `json:"hr_resize_x,omitempty"`
	HrResizeY                         *int64                  `json:"hr_resize_y,omitempty"`
	HrSamplerName                     *string                 `json:"hr_sampler_name,omitempty"`
	HrScale                           *int64                  `json:"hr_scale,omitempty"`
	HrSecondPassSteps                 *int64                  `json:"hr_second_pass_steps,omitempty"`
	HrUpscaler                        *string                 `json:"hr_upscaler,omitempty"`
	NIter                             *int64                  `json:"n_iter,omitempty"`
	NegativePrompt                    *string                 `json:"negative_prompt,omitempty"`
	OverrideSettings                  *map[string]interface{} `json:"override_settings,omitempty"`
	OverrideSettingsRestoreAfterwards *bool                   `json:"override_settings_restore_afterwards,omitempty"`
	Prompt                            *string                 `json:"prompt,omitempty"`
	RestoreFaces                      *bool                   `json:"restore_faces,omitempty"`
	SChurn                            *int64                  `json:"s_churn,omitempty"`
	SMinUncond                        *int64                  `json:"s_min_uncond,omitempty"`
	SNoise                            *int64                  `json:"s_noise,omitempty"`
	STmax                             *int64                  `json:"s_tmax,omitempty"`
	STmin                             *int64                  `json:"s_tmin,omitempty"`
	SamplerIndex                      *string                 `json:"sampler_index,omitempty"`
	SamplerName                       *string                 `json:"sampler_name,omitempty"`
	SaveDir                           *string                 `json:"save_dir,omitempty"`
	SaveImages                        *bool                   `json:"save_images,omitempty"`
	ScriptArgs                        *[]interface{}          `json:"script_args,omitempty"`
	ScriptName                        *string                 `json:"script_name,omitempty"`
	SdVae                             *string                 `json:"sd_vae,omitempty"`
	Seed                              *int64                  `json:"seed,omitempty"`
	SeedResizeFromH                   *int64                  `json:"seed_resize_from_h,omitempty"`
	SeedResizeFromW                   *int64                  `json:"seed_resize_from_w,omitempty"`
	SendImages                        *bool                   `json:"send_images,omitempty"`
	StableDiffusionModel              string                  `json:"stable_diffusion_model"`
	Steps                             *int64                  `json:"steps,omitempty"`
	Styles                            *[]string               `json:"styles,omitempty"`
	Subseed                           *int64                  `json:"subseed,omitempty"`
	SubseedStrength                   *float32                `json:"subseed_strength,omitempty"`
	Tiling                            *bool                   `json:"tiling,omitempty"`
	Width                             *int64                  `json:"width,omitempty"`
}

// UserLoginRequest user login request, include username and password
type UserLoginRequest struct {
	Password string `json:"password"`
	UserName string `json:"userName"`
}

// UserLoginResponse user login response
type UserLoginResponse struct {
	Message  *string `json:"message,omitempty"`
	Token    string  `json:"token"`
	UserName string  `json:"userName"`
}

// BatchUpdateResourceJSONRequestBody defines body for BatchUpdateResource for application/json ContentType.
type BatchUpdateResourceJSONRequestBody = BatchUpdateSdResourceRequest

// DelSDFuncJSONRequestBody defines body for DelSDFunc for application/json ContentType.
type DelSDFuncJSONRequestBody = DelSDFunctionRequest

// ExtraImagesJSONRequestBody defines body for ExtraImages for application/json ContentType.
type ExtraImagesJSONRequestBody = ExtraImagesRequest

// Img2ImgJSONRequestBody defines body for Img2Img for application/json ContentType.
type Img2ImgJSONRequestBody = Img2ImgRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = UserLoginRequest

// RegisterModelJSONRequestBody defines body for RegisterModel for application/json ContentType.
type RegisterModelJSONRequestBody = ModelAttributes

// UpdateModelJSONRequestBody defines body for UpdateModel for application/json ContentType.
type UpdateModelJSONRequestBody = ModelAttributes

// UpdateOptionsJSONRequestBody defines body for UpdateOptions for application/json ContentType.
type UpdateOptionsJSONRequestBody = OptionRequest

// Txt2ImgJSONRequestBody defines body for Txt2Img for application/json ContentType.
type Txt2ImgJSONRequestBody = Txt2ImgRequest
